config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"
  get "/search", to: "home#search"
  resources :dishes, only: %i(show)
  resources :categories, only: %i(show)
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :dishes, dependent: :destroy
end

app/models/dish.rb
# frozen_string_literal: true

class Dish < ApplicationRecord
  belongs_to :category
  has_many :dish_ingredients, dependent: :destroy

  scope :get_dishes, ->(name) { where('name like ?', "%#{sanitize_sql_like(name)}%") }
end

app/models/dish_ingredient.rb
# frozen_string_literal: true

class DishIngredient < ApplicationRecord
  belongs_to :dish
  belongs_to :ingredient
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  has_many :dish_ingredients, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @dishes = @category.dishes
  end
end

app/controllers/dishes_controller.rb
# frozen_string_literal: true

class DishesController < ApplicationController
  def show
    @dish = Dish.find(params[:id])
    @suggest_dishes = @dish.category.dishes.where.not(id: @dish.id)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @dishes = Dish.all.includes(:category)
    @categories = Category.all
  end

  def search
    @search_dishes = Dish.get_dishes(params[:name])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/categories/show.html.erb
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">Recipe</li>
    <li class="breadcrumb-item"><%= @category.name %></li>
  </ol>
</nav>

<% if @dishes.present? %>
  <div class="d-flex flex-wrap">
    <% @dishes.each do |dish| %>
      <div class="col-4 p-3">
        <%= render dish %>
      </div>
    <% end %>
  </div>
<% else %>
  <p>Dont have any recipe</p>
<% end %>

app/views/dishes/_dish.html.erb
<div class="card my-3">
  <img src="<%= dish.image %>" class="card-img-top">
  <div class="card-body">
    <h5 class="card-title"><%= link_to dish.name , dish , class: "text-decoration-none text-reset" %></h5>
    <p class="card-text"><%= dish.description %></p>
    <button type="button" class="btn btn-outline-primary" disabled><%= dish.category.name %></button>
  </div>
</div>

app/views/dishes/show.html.erb
<div class="row">
  <div class="col-9">
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">Recipe</li>
        <li class="breadcrumb-item"><%= @dish.category.name %></li>
        <li class="breadcrumb-item active" aria-current="page"><%= @dish.name %></li>
      </ol>
    </nav>
    <div class="row">
      <div class="col-5 p-3 d-flex justify-content-between">
        <img src="<%= @dish.image %>" class="img-fluid" height="180">
      </div>
      <div class="col-7">
        <%= simple_format(@dish.cooking) %>
      </div>
    </div>
  </div>
  <div class="col-3 p-3">
    <ul class="list-group">
      <h5>Ingredient List</h5>
      <% @dish.dish_ingredients.each do |dish_ingredient| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div>
            <input class="form-check-input me-1" type="checkbox" value="" aria-label="...">
            <%= dish_ingredient.ingredient.name %>
          </div>
          <span class="badge bg-primary rounded-pill"><%= dish_ingredient.measurement %></span>
        </li>
      <% end %>
    </ul>

    <% if @suggest_dishes.present? %>
      <h5 class="mt-3">Suggest</h5>
        <div class="overflow-auto" style="height: 420px">
          <% @suggest_dishes.each do |dish| %>
            <%= render dish %>
          <% end %>
        </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="col-3 p-3">
    <h4>Category</h4>
    <ul class="list-group">
      <% @categories.each do |category| %>
        <li class="list-group-item list-group-item-action m-1 border rounded-1"><%= link_to category.name , category , class: "text-decoration-none text-reset" %></li>
      <% end %>
    </ul>
  </div>
  <div class="col-9">
    <div class="d-flex flex-wrap">
      <% @dishes.each do |dish| %>
        <div class="col-4 p-3">
          <%= render dish %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/search.html.erb
<p>Search result</p>
<% if @search_dishes.present? %>
  <div class="d-flex flex-wrap">
    <% @search_dishes.each do |dish| %>
      <div class="col-4 p-3">
        <%= render dish %>
      </div>
    <% end %>
  </div>
<% else %>
  <p>Dont have any recipe</p>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-xl navbar-light navbar-custom shadow d-flex justify-content-center">
  <div class="container m-2" width="70%">
    <span class="navbar-brand mb-0 h1">
      <img src="https://cdn.iconscout.com/icon/premium/png-512-thumb/cooking-10-113588.png" alt="" width="40" height="40">
      <%= link_to "Recipe", root_path, class: "text-decoration-none text-reset"%>
    </span>
    <%= form_tag search_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :name, params[:name], class: "form-control me-2", placeholder: "Dish name" %>
      <%= submit_tag "Search", class: "btn btn-outline-success" %>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('cooking.png') %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="d-flex justify-content-center">
      <div class="container col-10 mt-5 p-3 border rounded-1">
        <%= yield %>
      </div>
    </div>
  </body>
</html>